### ISSUE TITLE
Scone unresponsive to gain access to their private helm repo

### ISSUE THREAD

**Issue by brunocous** [Azure-Samples/confidential-container-samples#6]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```
In order to deploy the confidential healthcare with scone sample on Kubernetes, one requires access to the private Scone Helm repo. 

As mentioned in https://sconedocs.github.io/helm/, one needs to send the Scone maintainers an email. I requested access to this repo. They replied saying that I should just play with the Scone playground on the Azure marketplace (https://sconedocs.github.io/azure/scone-playground/). This demo is not made with the Scone playground in mind.

To this day, I haven't heard anything back from Scone (despite sending gentle reminders), making this demo not deployable on AKS using their Helm charts. 

### workarounds
I have gained access to the images, and one can write their own Helm charts (or equivalent). Unfortunately I have no clue on how to correctly configure them, nor do I want to spend time reverse-engineering it.

### proposition
Azure confidential computing should push Scone to streamline the access to their private Helm chart repo. Or make the Scone helm repo public.

Or the demo should be adapted to use the relatively easy-to-access Scone playground.

**Comment by agowdamsft** [comment]
Sorry to hear this I will email this issue directly to Scone maintainers and ask for access. Please feel free to drop an email to me as well amgowda@microsoft.com

**Comment by scontain** [comment]
I'm very sorry about this! We granted you access to the community version the day you asked for access. I just checked the emails but I cannot find any of your emails regarding getting access to the helm charts. I will grant you access now to the helm charts.

**Comment by brunocous** [comment]
Hi Scontain, thank you for your reply and granting me access straight away. I am unblocked at last to try out the awesome stuff you have built. 👌
The request was sent with my private email instead of the professional one. Maybe they ended up in the spam folder? Anyway, I still believe that the helm charts could perfectly be made public without incurring excessive costs or leaking Scontain's secret sauce.
